# Generated by Django 2.2.6 on 2019-10-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='Movie title')),
                ('movie_imdb', models.FloatField(verbose_name='IMDB score')),
                ('movie_description', models.TextField(verbose_name='Movie Description')),
                ('movie_premiere', models.DateTimeField(verbose_name='Premiere date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Author of comment')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Comment')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
