# Generated by Django 2.2.6 on 2019-10-24 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 18, 52, 11, 359904, tzinfo=utc), verbose_name='published date'),
            preserve_default=False,
        ),
    ]
