# Generated by Django 2.2.6 on 2019-11-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=25, verbose_name='City')),
                ('cinema_adress', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='City')),
                ('tag', models.CharField(max_length=25, verbose_name='tag')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='film_id',
            field=models.IntegerField(default=0, verbose_name='film_id'),
            preserve_default=False,
        ),
    ]
