# Generated by Django 2.2.6 on 2019-11-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191128_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='film_id',
        ),
    ]
