# Generated by Django 2.2.6 on 2019-11-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_film_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movies.Cities'),
            preserve_default=False,
        ),
    ]
