# Generated by Django 2.2.6 on 2019-12-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_cinema_city_id'),
        ('movies', '0005_auto_20191128_1816'),
    ]

    operations = [
    ]
