# Generated by Django 2.2.6 on 2019-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_merge_20191205_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city_id',
            field=models.IntegerField(verbose_name='city_id'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='cinema_id',
            field=models.IntegerField(verbose_name='cinema_id_for_session'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='film_id',
            field=models.IntegerField(verbose_name='film_id_for_session'),
        ),
    ]
