# Generated by Django 2.2.6 on 2019-12-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20191205_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='ticket_type',
        ),
    ]
