# Generated by Django 2.2.6 on 2019-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_sessions_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_date',
            field=models.CharField(max_length=30, verbose_name='Session_date'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_time',
            field=models.CharField(max_length=30, verbose_name='Session_time'),
        ),
    ]
