# Generated by Django 2.2.6 on 2019-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20191205_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_hall',
            field=models.CharField(max_length=30, verbose_name='Session hall'),
        ),
    ]
