# Generated by Django 2.2.6 on 2019-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20191205_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_id',
            field=models.IntegerField(default=0, verbose_name='cinema_id'),
            preserve_default=False,
        ),
    ]
