# Generated by Django 2.2.6 on 2019-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_cinema_cinema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_id',
            field=models.IntegerField(default=0, verbose_name='film_id'),
            preserve_default=False,
        ),
    ]
