# Generated by Django 2.2.6 on 2019-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_movie_film_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='theatre_id',
            field=models.IntegerField(default=0, verbose_name='theatres_id'),
            preserve_default=False,
        ),
    ]
