# Generated by Django 2.2.6 on 2019-12-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_cinema_theatre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_adress',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
    ]
