# Generated by Django 2.2.6 on 2019-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20191208_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cinema_name',
            field=models.CharField(max_length=40, verbose_name='City'),
        ),
    ]
